In [1]:
import pandas as pd
import quandl

In [2]:
df = quandl.get("WIKI/GOOGL")

LimitExceededError: (Status 429) (Quandl Error QELx01) You have exceeded the anonymous user limit of 50 calls per day. To make more calls today, please register for a free Quandl account and then include your API key with your requests.

In [3]:
df.head()

Open    High     Low    Close      Volume  Ex-Dividend  \
Date                                                                   
2004-08-19  100.01  104.06   95.96  100.335  44659000.0          0.0   
2004-08-20  101.01  109.08  100.50  108.310  22834300.0          0.0   
2004-08-23  110.76  113.48  109.05  109.400  18256100.0          0.0   
2004-08-24  111.24  111.60  103.57  104.870  15247300.0          0.0   
2004-08-25  104.76  108.00  103.88  106.000   9188600.0          0.0   

            Split Ratio  Adj. Open  Adj. High   Adj. Low  Adj. Close  \
Date                                                                   
2004-08-19          1.0  50.159839  52.191109  48.128568   50.322842   
2004-08-20          1.0  50.661387  54.708881  50.405597   54.322689   
2004-08-23          1.0  55.551482  56.915693  54.693835   54.869377   
2004-08-24          1.0  55.792225  55.972783  51.945350   52.597363   
2004-08-25          1.0  52.542193  54.167209  52.100830   53.164113   

            Adj. Volume  
Date                     
2004-08-19   44659000.0  
2004-08-20   22834300.0  
2004-08-23   18256100.0  
2004-08-24   15247300.0  
2004-08-25    9188600.0

In [4]:
# choosing relevant columns
df = df[['Adj. Open',  'Adj. High',  'Adj. Low',  'Adj. Close', 'Adj. Volume']]

In [5]:
#Adding new columns
df['HL_PCT'] = (df['Adj. High'] - df['Adj. Low']) / df['Adj. Low'] * 100.0

In [6]:
df['PCT_change'] = (df['Adj. Close'] - df['Adj. Open']) / df['Adj. Open'] * 100.0


In [7]:
# define new data
df = df[['Adj. Close', 'HL_PCT', 'PCT_change', 'Adj. Volume']]
print(df.head())

            Adj. Close    HL_PCT  PCT_change  Adj. Volume
Date                                                     
2004-08-19   50.322842  8.441017    0.324968   44659000.0
2004-08-20   54.322689  8.537313    7.227007   22834300.0
2004-08-23   54.869377  4.062357   -1.227880   18256100.0
2004-08-24   52.597363  7.753210   -5.726357   15247300.0
2004-08-25   53.164113  3.966115    1.183658    9188600.0


In [8]:
import math
import numpy as np
from sklearn import preprocessing

In [9]:
forecast_col = 'Adj. Close'
#handle missing values
df.fillna(value=-99999, inplace=True)
#forecast out 1% of the entire length of the dataset.
forecast_out = int(math.ceil(0.01 * len(df)))

In [10]:
df.shape

(3424, 4)

In [11]:
df

Adj. Close    HL_PCT  PCT_change  Adj. Volume
Date                                                      
2004-08-19    50.322842  8.441017    0.324968   44659000.0
2004-08-20    54.322689  8.537313    7.227007   22834300.0
2004-08-23    54.869377  4.062357   -1.227880   18256100.0
2004-08-24    52.597363  7.753210   -5.726357   15247300.0
2004-08-25    53.164113  3.966115    1.183658    9188600.0
2004-08-26    54.122070  3.143512    2.820391    7094800.0
2004-08-27    53.239345  2.772258   -1.803885    6211700.0
2004-08-30    51.162935  3.411430   -3.106003    5196700.0
2004-08-31    51.343492  1.517228    0.048866    4917800.0
2004-09-01    50.280210  3.310926   -2.385589    9138200.0
2004-09-02    50.912161  3.466748    2.442224   15118600.0
2004-09-03    50.159839  2.436569   -0.931154    5152400.0
2004-09-07    50.947269  2.399357    0.564301    5847500.0
2004-09-08    51.308384  2.517413    1.548541    4985600.0
2004-09-09    51.313400  1.693069   -0.185366    4061700.0
2004-09-10    52.828075  5.192498    3.804080    8698800.0
2004-09-13    53.916435  1.831674    0.815905    7844100.0
2004-09-14    55.917612  4.878734    3.769546   10828900.0
2004-09-15    56.173402  3.656987    1.302460   10713000.0
2004-09-16    57.161452  3.716973    1.450952    9266300.0
2004-09-17    58.926902  3.469837    2.683097    9472500.0
2004-09-20    59.864797  4.136336    2.060710   10628700.0
2004-09-21    59.102444  2.476385   -1.963394    7228700.0
2004-09-22    59.373280  2.448421    0.791826    7581200.0
2004-09-23    60.597057  4.794052    1.666106    8535600.0
2004-09-24    60.100525  3.623914   -0.942382    9123400.0
2004-09-27    59.313094  2.614601   -1.087320    7066100.0
2004-09-28    63.626409  5.981200    4.713165   16929000.0
2004-09-29    65.742942  6.963479    3.595985   30516400.0
2004-09-30    65.000651  2.558140   -0.230179   13758000.0
...                 ...       ...         ...          ...
2018-02-13  1054.140000  1.365911    0.394286    1574121.0
2018-02-14  1072.700000  2.445228    1.743304    2029979.0
2018-02-15  1091.360000  2.517733    0.730075    1806206.0
2018-02-16  1095.500000  1.535431    0.193894    1971928.0
2018-02-20  1103.590000  2.411927    0.991068    1646405.0
2018-02-21  1113.750000  2.590496    0.419259    2024534.0
2018-02-22  1109.900000  1.837760   -0.828292    1386115.0
2018-02-23  1128.090000  1.854859    0.842973    1234539.0
2018-02-26  1143.700000  1.315813    1.046066    1489118.0
2018-02-27  1117.510000  2.458833   -2.289936    2094863.0
2018-02-28  1103.920000  2.234814   -1.611408    2431023.0
2018-03-01  1071.410000  4.120717   -3.436559    2766856.0
2018-03-02  1084.140000  3.502490    2.472637    2508145.0
2018-03-05  1094.760000  2.696149    1.542486    1432369.0
2018-03-06  1100.900000  1.016903   -0.108883    1169068.0
2018-03-07  1115.040000  2.412126    2.033272    1537429.0
2018-03-08  1129.380000  1.274615    1.090226    1510478.0
2018-03-09  1160.840000  2.354777    1.872751    2070174.0
2018-03-12  1165.930000  1.635611    0.075533    2129297.0
2018-03-13  1139.910000  3.827882   -2.723945    2129435.0
2018-03-14  1148.890000  1.524051    0.269681    2033697.0
2018-03-15  1150.610000  2.363383    0.090469    1623868.0
2018-03-16  1134.420000  2.249505   -1.811572    2654602.0
2018-03-19  1100.070000  2.796349   -1.582630    3076349.0
2018-03-20  1095.800000  2.136878   -0.236708    2709310.0
2018-03-21  1094.000000  1.976619    0.130884    1990515.0
2018-03-22  1053.150000  3.265882   -2.487014    3418154.0
2018-03-23  1026.550000  4.089299   -2.360729    2413517.0
2018-03-26  1054.090000  4.818025    0.332191    3272409.0
2018-03-27  1006.940000  6.707965   -5.353887    2940957.0

[3424 rows x 4 columns]

In [12]:
df['label'] = df[forecast_col].shift(-forecast_out)

In [13]:
df

Adj. Close    HL_PCT  PCT_change  Adj. Volume      label
Date                                                                 
2004-08-19    50.322842  8.441017    0.324968   44659000.0  69.078238
2004-08-20    54.322689  8.537313    7.227007   22834300.0  67.839414
2004-08-23    54.869377  4.062357   -1.227880   18256100.0  68.912727
2004-08-24    52.597363  7.753210   -5.726357   15247300.0  70.668146
2004-08-25    53.164113  3.966115    1.183658    9188600.0  71.219849
2004-08-26    54.122070  3.143512    2.820391    7094800.0  72.278116
2004-08-27    53.239345  2.772258   -1.803885    6211700.0  74.810934
2004-08-30    51.162935  3.411430   -3.106003    5196700.0  74.199045
2004-08-31    51.343492  1.517228    0.048866    4917800.0  70.462511
2004-09-01    50.280210  3.310926   -2.385589    9138200.0  74.921275
2004-09-02    50.912161  3.466748    2.442224   15118600.0  86.481962
2004-09-03    50.159839  2.436569   -0.931154    5152400.0  93.990139
2004-09-07    50.947269  2.399357    0.564301    5847500.0  91.181468
2004-09-08    51.308384  2.517413    1.548541    4985600.0  93.272925
2004-09-09    51.313400  1.693069   -0.185366    4061700.0  96.949273
2004-09-10    52.828075  5.192498    3.804080    8698800.0  95.615155
2004-09-13    53.916435  1.831674    0.815905    7844100.0  98.318500
2004-09-14    55.917612  4.878734    3.769546   10828900.0  97.736704
2004-09-15    56.173402  3.656987    1.302460   10713000.0  96.131750
2004-09-16    57.161452  3.716973    1.450952    9266300.0  92.635958
2004-09-17    58.926902  3.469837    2.683097    9472500.0  84.937193
2004-09-20    59.864797  4.136336    2.060710   10628700.0  86.542147
2004-09-21    59.102444  2.476385   -1.963394    7228700.0  84.611187
2004-09-22    59.373280  2.448421    0.791826    7581200.0  84.189886
2004-09-23    60.597057  4.794052    1.666106    8535600.0  91.793357
2004-09-24    60.100525  3.623914   -0.942382    9123400.0  91.281778
2004-09-27    59.313094  2.614601   -1.087320    7066100.0  92.721222
2004-09-28    63.626409  5.981200    4.713165   16929000.0  86.539640
2004-09-29    65.742942  6.963479    3.595985   30516400.0  86.517070
2004-09-30    65.000651  2.558140   -0.230179   13758000.0  84.029391
...                 ...       ...         ...          ...        ...
2018-02-13  1054.140000  1.365911    0.394286    1574121.0        NaN
2018-02-14  1072.700000  2.445228    1.743304    2029979.0        NaN
2018-02-15  1091.360000  2.517733    0.730075    1806206.0        NaN
2018-02-16  1095.500000  1.535431    0.193894    1971928.0        NaN
2018-02-20  1103.590000  2.411927    0.991068    1646405.0        NaN
2018-02-21  1113.750000  2.590496    0.419259    2024534.0        NaN
2018-02-22  1109.900000  1.837760   -0.828292    1386115.0        NaN
2018-02-23  1128.090000  1.854859    0.842973    1234539.0        NaN
2018-02-26  1143.700000  1.315813    1.046066    1489118.0        NaN
2018-02-27  1117.510000  2.458833   -2.289936    2094863.0        NaN
2018-02-28  1103.920000  2.234814   -1.611408    2431023.0        NaN
2018-03-01  1071.410000  4.120717   -3.436559    2766856.0        NaN
2018-03-02  1084.140000  3.502490    2.472637    2508145.0        NaN
2018-03-05  1094.760000  2.696149    1.542486    1432369.0        NaN
2018-03-06  1100.900000  1.016903   -0.108883    1169068.0        NaN
2018-03-07  1115.040000  2.412126    2.033272    1537429.0        NaN
2018-03-08  1129.380000  1.274615    1.090226    1510478.0        NaN
2018-03-09  1160.840000  2.354777    1.872751    2070174.0        NaN
2018-03-12  1165.930000  1.635611    0.075533    2129297.0        NaN
2018-03-13  1139.910000  3.827882   -2.723945    2129435.0        NaN
2018-03-14  1148.890000  1.524051    0.269681    2033697.0        NaN
2018-03-15  1150.610000  2.363383    0.090469    1623868.0        NaN
2018-03-16  1134.420000  2.249505   -1.811572    2654602.0        NaN
2018-03-19  1100.070000  2.796349   -1.582630    3076349.0        NaN
2018-03-20  1095.800000

In [14]:
df.dropna(inplace=True)

In [15]:
#Scikit-learn actually fundamentally requires numpy arrays. 
# Pandas dataframes can be easily converted to NumPy arrays
X = np.array(df.drop(labels='label',axis=1))

In [16]:
X

array([[ 5.03228418e+01,  8.44101709e+00,  3.24967503e-01,
         4.46590000e+07],
       [ 5.43226889e+01,  8.53731343e+00,  7.22700723e+00,
         2.28343000e+07],
       [ 5.48693765e+01,  4.06235672e+00, -1.22788010e+00,
         1.82561000e+07],
       ...,
       [ 1.18159000e+03,  1.54700007e+00,  4.76194525e-01,
         2.77496700e+06],
       [ 1.11920000e+03,  1.81160398e+00, -7.29098295e-01,
         5.79888000e+06],
       [ 1.06876000e+03,  5.51223574e+00, -2.89384977e+00,
         3.74246900e+06]])

In [17]:
Y = np.array(df['label'])

In [18]:
Y

array([  69.0782379 ,   67.83941377,   68.91272699, ..., 1026.55      ,
       1054.09      , 1006.94      ])

In [19]:
# Do some data preprocessing
# Generally, you want your features in machine learning to be in a range of -1 to 1. 
# This may do nothing, but it usually speeds up processing and can also help with accuracy.
X = preprocessing.scale(X)

In [20]:
X

array([[-1.41006544,  4.33430358,  0.23194449,  4.44790502],
       [-1.39402696,  4.4006455 ,  4.84146176,  1.80881376],
       [-1.39183486,  1.31769132, -0.80512254,  1.25520764],
       ...,
       [ 3.12606095, -0.41522584,  0.33294124, -0.61680539],
       [ 2.87589111, -0.23293095, -0.47201183, -0.25114711],
       [ 2.67363808,  2.31656369, -1.91773798, -0.4998129 ]])

In [21]:
from sklearn.model_selection import train_test_split

In [22]:
# create training and testing sets
X_train, X_test, Y_train, Y_test = train_test_split(X,Y,test_size=0.2) 

In [23]:
from sklearn.svm import SVR
import numpy as np

In [24]:
from sklearn.model_selection import GridSearchCV
# use gridsearchcv for selecting parameters
# grid search C, gamma of rbf kernel
# For an initial search, a logarithmic grid with basis
# 10 is often helpful. Using a basis of 2, a finer
# tuning can be achieved but at a much higher cost.

C_range = np.logspace(-1, 5, 5)
gamma_range = np.logspace(-5, 3, 5)
param_grid = dict(gamma=gamma_range, C=C_range)

grid = GridSearchCV(estimator = SVR(kernel='rbf'), param_grid = param_grid,cv=3)
grid_result = grid.fit(X_train, Y_train)

In [25]:
# summarize results
print("Best: %f using %s" % (grid_result.best_score_, grid_result.best_params_))

Best: 0.978027 using {'C': 100000.0, 'gamma': 0.001}


In [26]:
# Create model - see documentation for parameter details
clf = SVR(C=100000,kernel='rbf',gamma=0.001)

In [27]:
# Fit data
clf.fit(X_train, Y_train)

SVR(C=100000, cache_size=200, coef0=0.0, degree=3, epsilon=0.1, gamma=0.001,
  kernel='rbf', max_iter=-1, shrinking=True, tol=0.001, verbose=False)

In [28]:
# Get parameters for this estimator.
clf.get_params()

{'C': 100000,
 'cache_size': 200,
 'coef0': 0.0,
 'degree': 3,
 'epsilon': 0.1,
 'gamma': 0.001,
 'kernel': 'rbf',
 'max_iter': -1,
 'shrinking': True,
 'tol': 0.001,
 'verbose': False}

In [29]:
# Test on testset
prediction = clf.predict(X_test)

In [30]:
#Returns the coefficient of determination R^2 of the prediction.
Rsquared = clf.score(X_test,Y_test)

In [31]:
Rsquared

0.9790924392642748